 # Example Astropix3 config
#
# The following yaml should comply to the structure below.
# It is important, that the order of configbits under the config section, corresponds to the actual order in the chip
#
# astropix<version>:
#   geometry:
#       cols: <number of cols>
#       rows: <number of rows>
#   config:
#       <group-name>:
#           <configbit-name>: [<number of bits>, <value>]
#   ...
#
---
astropix3:
    chain:
        length: 1
    geometry:
        cols: 35
        rows: 35
    config:
        digitalconfig:
            interrupt_pushpull: [1, 0b1]
            en_inj:             [18, 0b0]
            reset:              [1, 0b0]
            extrabits:          [15, 0b0]

        biasconfig:
            DisHiDR:            [1, 0b0]
            q01:                [1, 0b0]
            qon0:               [1, 0b0]
            qon1:               [1, 0b1]
            qon2:               [1, 0b0]
            qon3:               [1, 0b1]

        idacs:
            blres:              [6, 0]
            nu1:                [6, 0]
            vn1:                [6, 20]
            vnfb:               [6, 3]
            vnfoll:             [6, 4]
            nu5:                [6, 0]
            nu6:                [6, 0]
            nu7:                [6, 0]
            nu8:                [6, 0]
            vn2:                [6, 0]
            vnfoll2:            [6, 10]
            vnbias:             [6, 10]
            vpload:             [6, 5]
            nu13:               [6, 60]
            vncomp:             [6, 2]
            vpfoll:             [6, 60]
            nu16:               [6, 0]
            vprec:              [6, 60]
            vnrec:              [6, 30]

        vdacs:
            blpix:              [10, 568]
            thpix:              [10, 682]
            vcasc2:             [10, 625]
            nu1:                [10, 512]
            thpmos:             [10, 682]
            vinj:               [10, 171] 

        recconfig:
            col0:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col1:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col2:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col3:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col4:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col5:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col6:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col7:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col8:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col9:               [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col10:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col11:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col12:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col13:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col14:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col15:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col16:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col17:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col18:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col19:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col20:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col21:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col22:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col23:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col24:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col25:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col26:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col27:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col28:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col29:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col30:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col31:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col32:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col33:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
            col34:              [38, 0b001_11111_11111_11111_11111_11111_11111_11110]
